const cloths = ['Traditional','Western','Simple']
cloths.forEach(function(value,index){
    console.log('Clothes = ',value)
})
const cloth = Array.isArray(cloths)
console.log('Is Array or Not = ',cloth)
const cloth1 = cloths.includes('Simple',1)
console.log('Includes or Not = ',cloth1)
const cloth2 = cloths.push('NightDresses')
console.log('After Push Method = ',cloth2)
const cloth3 = cloths.pop()
console.log('After Pop Method = ',cloth3)
const cloth4 = cloths.unshift('DailyWear','FunctionWear')
console.log('After Unshift Method = ',cloth4)
const cloth5 = cloths.shift()
console.log('After Shift Method = ',cloth5)
const cloth6 = cloths.splice(1,3,'Sportsdress','NightDresses')
console.log('After splice Method = ',cloth6)
const cloth7 = cloths.slice(1,2)
console.log('After Slice Method = ',cloth7)
const cloth8 = cloths.indexOf('Simple',1)
console.log('After IndexOf Method = ',cloth8)
const cloth9 = cloths.join('-')
console.log('After Join Method = ',cloth9)


const fruits = ['Grapes','Orange','WaterMelon','Mango']
fruits.forEach(function(value,index){
    console.log('Fruits = ',value)
})
const fruit = Array.isArray(fruits)
console.log('Is Array or Not = ',fruit)
const fruit1 = fruits.includes('Orange',1)
console.log('Includes or Not = ',fruit1)
const fruit2 = fruits.push('Apple')
console.log('After Push Method = ',fruit2)
const fruit3 = fruits.pop()
console.log('After Pop Method = ',fruit3)
const fruit4 = fruits.unshift('Banana','Pineapple')
console.log('After Unshift Method = ',fruit4)
const fruit5 = fruits.shift()
console.log('After Shift Method = ',fruit5)
const fruit6 = fruits.splice(1,3,'Kiwi','Banana')
console.log('After splice Method = ',fruit6)
const fruit7 = fruits.slice(1,2)
console.log('After Slice Method = ',fruit7)
const fruit8 = fruits.indexOf('Mango',2)
console.log('After IndexOf Method = ',fruit8)
const fruit9 = fruits.join('-')
console.log('After Join Method = ',fruit9)

const vegs = ['Carrot','Raddish','Cabage']
vegs.forEach(function(value,index){
    console.log('Vegitables = ',value)
})
const veg = Array.isArray(vegs)
console.log('Is Array or Not = ',veg)
const veg1 = vegs.includes('Raddish',1)
console.log('Includes or Not = ',veg1)
const veg2 = vegs.push('Drumstick')
console.log('After Push Method = ',veg2)
const veg3 = vegs.pop()
console.log('After Pop Method = ',veg3)
const veg4 = vegs.unshift('Onion','Beetroot')
console.log('After Unshift Method = ',veg4)
const veg5 = vegs.shift()
console.log('After Shift Method = ',veg5)
const veg6 = vegs.splice(1,3,'Garlic','Onion')
console.log('After splice Method = ',veg6)
const veg7 = vegs.slice(1,2)
console.log('After Slice Method = ',veg7)
const veg8 = vegs.indexOf('Mango',2)
console.log('After IndexOf Method = ',veg8)
const veg9 = vegs.join('-')
console.log('After Join Method = ',veg9)

const nums = [0,1,2,3,4]
nums.forEach(function(value,index){
    console.log('nums = ',value)
})
const num = Array.isArray(fruits)
console.log('Is Array or Not = ',num)
const num1 = nums.includes(1,1)
console.log('Includes or Not = ',num1)
const num2 = nums.push(4)
console.log('After Push Method = ',num2)
const num3 = nums.pop()
console.log('After Pop Method = ',num3)
const num4 = nums.unshift(5,6)
console.log('After Unshift Method = ',num4)
const num5 = nums.shift()
console.log('After Shift Method = ',num5)
const num6 = nums.splice(1,3,3,5)
console.log('After splice Method = ',num6)
const num7 = nums.slice(1,2)
console.log('After Slice Method = ',num7)
const num8 = nums.indexOf('2',2)
console.log('After IndexOf Method = ',num8)
const num9 = nums.join('-')
console.log('After Join Method = ',num9)

const names = ['Sai','Sri','Hema','Harika']
names.forEach(function(value,index){
    console.log('names = ',value)
})
const name = Array.isArray(names)
console.log('Is Array or Not = ',name)
const name1 = names.includes('Sri',1)
console.log('Includes or Not = ',name1)
const name2 = names.push('Suchi')
console.log('After Push Method = ',name2)
const name3 = names.pop()
console.log('After Pop Method = ',name3)
const name4 = names.unshift('Janu','Pranu')
console.log('After Unshift Method = ',name4)
const name5 = names.shift()
console.log('After Shift Method = ',name5)
const name6 = names.splice(1,3,'Mouni','Harika')
console.log('After splice Method = ',name6)
const name7 = names.slice(1,2)
console.log('After Slice Method = ',name7)
const name8 = names.indexOf('Mouni',1)
console.log('After IndexOf Method = ',name8)
const name9 = names.join('-')
console.log('After Join Method = ',name9)

const days = ['Mon','Tue','Wed']
days.forEach(function(value,index){
    console.log('days = ',value)
})
const day = Array.isArray(days)
console.log('Is Array or Not = ',day)
const day1 = days.includes('Tue',1)
console.log('Includes or Not = ',day1)
const day2 = days.push('Thu')
console.log('After Push Method = ',day2)
const day3 = days.pop()
console.log('After Pop Method = ',day3)
const day4 = days.unshift('Fri','Sat')
console.log('After Unshift Method = ',day4)
const day5 = days.shift()
console.log('After Shift Method = ',day5)
const day6 = days.splice(1,3,'Sun','Fri')
console.log('After splice Method = ',day6)
const day7 = days.slice('Wed',1)
console.log('After Slice Method = ',day7)
const day8 = days.indexOf('Thu',0)
console.log('After IndexOf Method = ',day8)
const day9 = days.join('-')
console.log('After Join Method = ',day9)

const colors = ['Red','Blue','Green']
colors.forEach(function(value,index){
    console.log('days = ',value)
})
const color = Array.isArray(colors)
console.log('Is Array or Not = ',color)
const color1 = colors.includes('Blue',1)
console.log('Includes or Not = ',color1)
const color2 = colors.push('Orange')
console.log('After Push Method = ',color2)
const color3 = colors.pop()
console.log('After Pop Method = ',color3)
const color4 = colors.unshift('Grey','Black')
console.log('After Unshift Method = ',color4)
const color5 = colors.shift()
console.log('After Shift Method = ',color5)
const color6 = colors.splice(1,3,'White','Green')
console.log('After splice Method = ',color6)
const color7 = colors.slice('Blue',1)
console.log('After Slice Method = ',color7)
const color8 = colors.indexOf('Red',0)
console.log('After IndexOf Method = ',color8)
const color9 = colors.join(',')
console.log('After Join Method = ',color9)

const months = ['Jan','Feb','March']
months.forEach(function(value,index){
    console.log('days = ',value)
})
const month = Array.isArray(months)
console.log('Is Array or Not = ',month)
const month1 = months.includes('Blue',1)
console.log('Includes or Not = ',month1)
const month2 = months.push('April')
console.log('After Push Method = ',month2)
const month3 = months.pop()
console.log('After Pop Method = ',month3)
const month4 = months.unshift('May','June')
console.log('After Unshift Method = ',month4)
const month5 = months.shift()
console.log('After Shift Method = ',month5)
const month6 = months.splice(1,3,'July','May')
console.log('After splice Method = ',month6)
const month7 = months.slice('Feb',1)
console.log('After Slice Method = ',month7)
const month8 = months.indexOf('June',0)
console.log('After IndexOf Method = ',month8)
const month9 = months.join(',')
console.log('After Join Method = ',month9)

const emps = ['Sai','A']
emps.forEach(function(value,index){
    console.log('emps = ',value)
})
const emp = Array.isArray(colors)
console.log('Is Array or Not = ',emp)
const emp1 = emps.includes('Blue',1)
console.log('Includes or Not = ',emp1)
const emp2 = emps.push('1998')
console.log('After Push Method = ',emp2)
const emp3 = emps.pop()
console.log('After Pop Method = ',emp3)
const emp4 = emps.unshift('AccN01','15000')
console.log('After Unshift Method = ',emp4)
const emp5 = emps.shift()
console.log('After Shift Method = ',emp5)
const emp6 = emps.splice(1,3,'Bonus','Accno')
console.log('After splice Method = ',emp6)
const emp7 = emps.slice('Bonus',1)
console.log('After Slice Method = ',emp7)
const emp8 = emps.indexOf('Accno',0)
console.log('After IndexOf Method = ',emp8)
const emp9 = emps.join(',')
console.log('After Join Method = ',emp9)

const subs = ['Math','English']
subs.forEach(function(value,index){
    console.log('subs = ',value)
})
const sub = Array.isArray(subs)
console.log('Is Array or Not = ',sub)
const sub1 = subs.includes('English',1)
console.log('Includes or Not = ',sub1)
const sub2 = subs.push('Science')
console.log('After Push Method = ',sub2)
const sub3 = subs.pop()
console.log('After Pop Method = ',sub3)
const sub4 = subs.unshift('Social','Hindi')
console.log('After Unshift Method = ',sub4)
const sub5 = subs.shift()
console.log('After Shift Method = ',sub5)
const sub6 = subs.splice(1,3,'Telugu','Social')
console.log('After splice Method = ',sub6)
const sub7 = subs.slice('Science',1)
console.log('After Slice Method = ',sub7)
const sub8 = subs.indexOf('Social',0)
console.log('After IndexOf Method = ',sub8)
const sub9 = subs.join(',')
console.log('After Join Method = ',sub9)
